import { calibrateDifficulties, dropdown as dd, mc, multi as ms, statements as sg } from './question-helpers.mjs';

const refs = {
  'cloud-computing': { title: 'Describe cloud computing', url: 'https://learn.microsoft.com/en-us/training/modules/describe-cloud-compute/' },
  'cloud-benefits': { title: 'Describe the benefits of using cloud services', url: 'https://learn.microsoft.com/en-us/training/modules/describe-benefits-use-cloud-services/' },
  'service-types': { title: 'Describe cloud service types', url: 'https://learn.microsoft.com/en-us/training/modules/describe-cloud-service-types/' },
  'azure-architecture': { title: 'Describe core Azure architectural components', url: 'https://learn.microsoft.com/en-us/training/modules/describe-core-architectural-components-of-azure/' },
  'compute-networking': { title: 'Describe Azure compute and networking services', url: 'https://learn.microsoft.com/en-us/training/modules/describe-azure-compute-networking-services/' },
  'azure-storage': { title: 'Describe Azure storage services', url: 'https://learn.microsoft.com/en-us/training/modules/describe-azure-storage-services/' },
  'identity-security': { title: 'Describe Azure identity, access, and security', url: 'https://learn.microsoft.com/en-us/training/modules/describe-azure-identity-access-security/' },
  'cost-management': { title: 'Describe cost management in Azure', url: 'https://learn.microsoft.com/en-us/training/modules/describe-cost-management-azure/' },
  'governance-compliance': { title: 'Describe Azure governance and compliance tools', url: 'https://learn.microsoft.com/en-us/training/modules/describe-features-tools-azure-for-governance-compliance/' },
  'management-deployment': { title: 'Describe tools for managing and deploying Azure resources', url: 'https://learn.microsoft.com/en-us/training/modules/describe-features-tools-manage-deploy-azure-resources/' },
  monitoring: { title: 'Describe monitoring tools in Azure', url: 'https://learn.microsoft.com/en-us/training/modules/describe-monitoring-tools-azure/' }
};

const p1 = [
  dd('cloud-computing','easy','{{blank}} describes paying for cloud resources as they are used instead of buying datacenter capacity in advance.','Consumption-based pricing',['Capital expenditure','High availability','Vertical scaling'],'Consumption-based pricing makes operating expense track actual use and lets a customer release resources it no longer needs. Capital expenditure pays up front for an asset, while the other choices describe availability or capacity.'),
  sg('cloud-computing','medium','For each task in a public-cloud virtual machine deployment, decide whether the customer is normally responsible.','yes-no',[["Configure access to the application",true],["Replace failed disks in the Azure datacenter",false],["Patch the physical host operating system",false]],'The customer secures its application and identities. Microsoft operates the physical datacenter, replaces host hardware, and maintains the virtualization host beneath an Azure virtual machine.'),
  ms('cloud-computing','hard','A company keeps regulated systems in its own datacenter and runs customer-facing services in Azure. Which TWO statements describe this design?',['It is a hybrid-cloud deployment','The company remains responsible for its on-premises infrastructure'],['It is exclusively a public-cloud deployment','Microsoft patches the company’s on-premises servers'],'Hybrid cloud combines private or on-premises resources with public-cloud services. The ownership boundary does not transfer maintenance of equipment that remains in the company’s datacenter to Microsoft.'),
  mc('cloud-computing','easy','A function runs when a queue message arrives, scales automatically, and exposes no server operating system to the developer. Which computing model is this?','Serverless computing',['Private cloud','Dedicated hosting','Desktop virtualization'],'Serverless computing lets a team run event-driven code while the provider manages host provisioning and scaling. The scenario does not describe privately owned infrastructure, a dedicated server, or a hosted desktop.'),
  mc('cloud-computing','medium','Who is responsible for classifying confidential customer records stored in a managed Azure database?','The organization that owns and uses the data',['Microsoft alone','The database engine without human policy','The organization’s internet provider'],'Data ownership and classification remain customer responsibilities in every cloud service model. Microsoft secures the underlying service, but it cannot decide the business sensitivity of the customer’s records.'),

  dd('cloud-benefits','easy','{{blank}} is demonstrated when a service continues to meet its uptime target after one component fails.','high availability',['capital expenditure','data classification','single tenancy'],'High availability concerns keeping a service accessible despite component failures or maintenance. The alternatives describe financial treatment, information governance, or isolation rather than uptime.'),
  sg('cloud-benefits','medium','Evaluate each statement about scaling and elasticity.','true-false',[["Horizontal scaling can add more instances",true],["Vertical scaling always removes instances when demand falls",false],["Elasticity can add and remove capacity in response to demand",true]],'Horizontal scaling changes the number of instances, while vertical scaling changes the capacity of an existing instance. Elasticity describes responsive expansion and contraction rather than a one-way resize.'),
  mc('cloud-benefits','medium','A retailer automatically adds application instances for a flash sale and removes them after traffic returns to normal. Which benefit is illustrated?','Elasticity',['Governance','Predictability','Capital ownership'],'Elasticity matches capacity to changing demand in both directions. Governance applies rules, predictability supports forecasting, and ownership of physical capital is not the cloud behavior shown.'),
  mc('cloud-benefits','hard','A team deploys the same tested template for development, test, and production. Which cloud benefit does this most directly improve?','Manageability through consistent deployment',['Data sovereignty through replication','Availability through larger invoices','Authentication through tagging'],'Repeatable templates make environments easier to deploy and control consistently, which is a manageability benefit. Templates alone do not determine data location, guarantee availability, or authenticate users.'),

  dd('service-types','easy','Developers use a {{blank}} model when they deploy code while the provider maintains the operating system and runtime.','platform as a service (PaaS)',['infrastructure as a service (IaaS)','software as a service (SaaS)','an on-premises private cloud'],'PaaS provides a managed application platform, so developers focus on code and data instead of patching the host operating system and runtime. IaaS exposes more administration, while SaaS supplies a complete application.'),
  sg('service-types','medium','For each customer requirement, decide whether infrastructure as a service (IaaS) is the best match.','yes-no',[["Install a legacy component that requires operating-system administrator access",true],["Use a complete payroll application without managing its code",false],["Deploy an API while the provider patches the runtime",false]],'IaaS is appropriate when the customer needs guest operating-system control. A complete business application is SaaS, and a managed application runtime is a PaaS characteristic.'),
  ms('service-types','hard','Which TWO responsibilities normally remain with a customer that runs an application on Azure virtual machines?',['Patch the guest operating system','Configure the application and its data'],['Maintain the Azure hypervisor','Replace physical datacenter networking equipment'],'Virtual machines are IaaS: the customer manages the guest operating system, installed software, configuration, and data. Microsoft operates the physical hosts, network fabric, and hypervisor.'),
  mc('service-types','easy','Employees use a provider-hosted email application in a browser and never manage its servers. Which service type is being consumed?','Software as a service (SaaS)',['Infrastructure as a service (IaaS)','Platform as a service (PaaS)','Colocation'],'SaaS delivers a complete provider-managed application to users. IaaS exposes infrastructure for customer administration, while PaaS provides a development and hosting platform rather than finished email software.'),
  mc('service-types','medium','A database team wants automated patching and backups but must retain control of schemas, queries, and stored data. Which service model is the closest fit?','Platform as a service (PaaS)',['Infrastructure as a service (IaaS)','Software as a service (SaaS)','Customer-owned hardware only'],'A managed database is commonly PaaS: the provider operates the platform while the customer manages database design and data. IaaS would leave more patching to the customer, and SaaS would expose a finished application.'),

  dd('azure-architecture','easy','{{blank}} is the Azure scope that can organize several subscriptions so policy and access assignments inherit to them.','A management group',['A resource group','An availability zone','A virtual network'],'Management groups sit above subscriptions in the Azure resource hierarchy and support inherited governance. Resource groups exist inside one subscription, while zones and virtual networks are not governance containers.'),
  sg('azure-architecture','medium','Evaluate each statement about resource groups.','true-false',[["A resource belongs to one resource group at a time",true],["Every resource in a resource group must be in the same Azure region",false],["A resource group can contain resources with a shared lifecycle",true]],'Resource groups are logical lifecycle and management containers within a subscription. They can include resources deployed in different regions, but an individual resource has one resource-group membership at a time.'),
  mc('azure-architecture','medium','A solution needs physically separate datacenter locations inside one Azure region, each with independent power and cooling. What should it use?','Availability zones',['Management groups','Resource tags','Azure Policy initiatives'],'Availability zones are fault-isolated physical locations within a supported region. Management groups, tags, and policy organize or govern resources but do not create datacenter-level isolation.'),
  mc('azure-architecture','hard','A company needs an independent billing and access-management boundary for a new business unit. Which Azure scope should it create?','A subscription',['An availability zone','A resource lock','A storage container'],'Subscriptions are Azure billing and access-control boundaries below management groups. Zones provide resiliency, locks protect changes, and storage containers organize data rather than accounts and governance.'),

  dd('compute-networking','easy','Use Azure {{blank}} for an event-driven task that should run without managing servers.','Functions',['Virtual Desktop','DNS','Data Box'],'Azure Functions provides serverless, event-driven compute and manages the underlying hosts. Virtual Desktop delivers user desktops, DNS resolves names, and Data Box transfers large offline datasets.'),
  sg('compute-networking','medium','For each requirement, decide whether Azure App Service is an appropriate solution.','yes-no',[["Host a web API on a managed application platform",true],["Provide a dedicated private circuit from an office to Azure",false],["Deliver complete Windows desktops to remote employees",false]],'App Service is managed hosting for web apps and APIs. ExpressRoute supplies a private circuit, while Azure Virtual Desktop supplies hosted Windows desktops and applications.'),
  ms('compute-networking','hard','An organization needs private connectivity between an on-premises network and Azure. Which TWO services can provide that connectivity?',['Azure VPN Gateway','Azure ExpressRoute'],['Azure DNS','Azure Cost Management'],'VPN Gateway can establish an encrypted tunnel over the internet, while ExpressRoute provides private dedicated connectivity through a provider. DNS resolves names and Cost Management analyzes spending.'),
  mc('compute-networking','easy','A stateless web tier needs identical virtual machines that can scale as demand changes. Which Azure service is designed for this pattern?','Azure Virtual Machine Scale Sets',['Azure Files','Microsoft Purview','Azure Service Health'],'Virtual Machine Scale Sets manage a group of load-balanced VM instances and support scaling. Files is storage, Purview governs data, and Service Health reports platform incidents.'),
  mc('compute-networking','medium','Two Azure virtual networks must exchange traffic privately over Microsoft’s backbone. Which feature should be configured?','Virtual network peering',['A public DNS zone','Azure Advisor','A storage lifecycle rule'],'Virtual network peering connects virtual networks so resources can communicate over private Azure routing. DNS, recommendations, and lifecycle policies do not establish network connectivity.'),

  dd('azure-storage','easy','Data that consists of images, backups, and other unstructured objects belongs in Azure {{blank}} Storage.','Blob',['Queue','Table','Disk'],'Blob Storage is Azure object storage for large amounts of unstructured data. Queues carry messages, Tables store schemaless key-value entities, and managed disks back virtual machines.'),
  sg('azure-storage','medium','Evaluate each statement about Azure Storage redundancy.','true-false',[["Locally redundant storage keeps copies in one datacenter",true],["Zone-redundant storage depends on only one availability zone",false],["Geo-redundant storage copies data to a secondary region",true]],'LRS protects within one datacenter, ZRS synchronously uses multiple availability zones, and GRS adds asynchronous replication to a paired secondary region. Each option addresses a different failure scope.'),
  ms('azure-storage','hard','Which TWO tools are specifically useful when moving or synchronizing file data with Azure Storage?',['AzCopy for command-line transfers','Azure File Sync for caching an Azure file share on Windows Server'],['Azure Policy for copying file contents','Azure Advisor for mounting a file share'],'AzCopy performs high-performance storage data transfers, while Azure File Sync synchronizes Azure file shares with Windows Servers. Policy evaluates configuration and Advisor makes recommendations; neither transfers files.'),
  mc('azure-storage','medium','A company must transfer hundreds of terabytes to Azure, but the site has insufficient network bandwidth. What should it use?','Azure Data Box',['Azure Monitor alerts','Azure DNS','Microsoft Entra ID'],'Azure Data Box provides Microsoft-managed appliances for large offline data transfers when a network upload is impractical. Monitoring, name resolution, and identity services do not transport the dataset.'),
  mc('azure-storage','hard','Compliance records are almost never read and can tolerate several hours before retrieval. Which Blob Storage access tier best minimizes storage cost?','Archive',['Hot','Premium','Transaction optimized'],'The archive tier offers the lowest storage cost for rarely accessed blobs in exchange for rehydration delay and higher retrieval cost. Hot and premium options prioritize frequent or low-latency access.'),

  dd('identity-security','easy','Requiring a password plus a verification prompt in an authenticator app is {{blank}}.','multifactor authentication (MFA)',['single sign-on (SSO)','resource tagging','geo-replication'],'MFA requires evidence from more than one authentication factor, reducing reliance on a stolen password. SSO reduces repeated sign-ins, while tagging and replication are unrelated to identity verification.'),
  ms('identity-security','hard','Which TWO practices are central to a Zero Trust strategy?',['Verify explicitly using available signals','Grant only the least privilege required'],['Trust requests because they originate on a corporate network','Give every administrator permanent Owner access'],'Zero Trust treats network location as insufficient proof, verifies each request with relevant signals, and limits access scope and duration. Implicit trust and broad standing privilege conflict with that approach.'),
  mc('identity-security','easy','Which Microsoft cloud service supplies identities and authentication for Azure resources and Microsoft 365?','Microsoft Entra ID',['Azure Monitor','Azure DNS','Azure Storage Explorer'],'Microsoft Entra ID is the cloud identity and access service used by Azure and Microsoft 365. The other services handle telemetry, name resolution, or storage administration.'),
  mc('identity-security','medium','A partner should use an existing external identity to access one selected business application. Which capability supports this?','Microsoft Entra External ID collaboration',['An availability set','Azure Blob lifecycle management','Azure Data Box'],'External identity collaboration lets organizations invite and govern partner access without creating a separate local password for every partner. The alternatives concern compute resilience, storage, or data transfer.'),
  mc('identity-security','medium','A user needs read-only access to virtual machines in one resource group. What is the most appropriate assignment?','The Reader Azure RBAC role at the resource-group scope',['The Owner role at the subscription scope','A delete lock on each virtual machine','A department tag on the resource group'],'Azure RBAC grants actions at a defined scope; Reader on the resource group supplies view access to its resources. Owner is excessive, and locks or tags do not grant user permissions.'),

  dd('cost-management','easy','To estimate the price of a proposed Azure solution before deploying it, use the Azure {{blank}}.','Pricing calculator',['Service Health dashboard','Policy compliance view','Activity log'],'The Pricing calculator estimates expected charges for a planned combination of Azure services and usage. Service Health, Policy, and the activity log report operational or governance information rather than forecast prices.'),
  ms('cost-management','hard','Which TWO actions can directly reduce cost for predictable or idle compute workloads?',['Purchase a reservation for eligible steady usage','Stop and deallocate development virtual machines when unused'],['Add more resource tags without changing usage','Apply a read-only lock to every virtual machine'],'Reservations can discount eligible long-running usage, and deallocation stops compute billing for unused VMs. Tags help allocation and locks protect configuration, but neither alone reduces consumed compute.'),
  mc('cost-management','medium','A finance team needs actual Azure spend grouped by department, but resources span many resource groups. What should teams apply consistently?','A department tag',['An availability-zone number','A private IP address','A resource lock'],'Tags attach business metadata that Cost Management can use to group and allocate charges. Zone numbers, addresses, and locks do not express department ownership in cost reports.'),
  mc('cost-management','medium','Which network activity is most likely to add a data-transfer charge to an Azure bill?','Sending data out of Azure to the internet',['Uploading data into Azure in a typical scenario','Renaming a resource group','Viewing a dashboard in the Azure portal'],'Outbound data transfer is a common pricing factor, with charges varying by destination and volume. Resource names and normal portal administration do not represent metered application data egress.'),

  sg('governance-compliance','medium','Evaluate each statement about Azure Policy and Azure RBAC.','true-false',[["Azure Policy can report resources that do not meet a rule",true],["Azure RBAC determines whether a user may delete a resource",true],["Azure Policy is the service that authenticates a user password",false]],'Policy evaluates resource configuration and compliance, whereas RBAC authorizes management actions at Azure scopes. User authentication is supplied by an identity service such as Microsoft Entra ID.'),
  ms('governance-compliance','hard','Which TWO controls can help prevent an accidental noncompliant production change?',['An Azure Policy assignment that restricts resource configuration','A resource lock that blocks deletion or modification'],['A resource tag used only for reporting','A pricing estimate saved before deployment'],'Policy evaluates or restricts configuration, while locks can block destructive management operations. Reporting metadata and cost estimates do not enforce the production resource state.'),
  mc('governance-compliance','easy','A company wants every new resource limited to an approved list of Azure regions. Which service should enforce the rule?','Azure Policy',['Azure DNS','Azure Advisor','Azure Functions'],'Azure Policy can deny or flag resource configurations that fall outside assigned rules, including allowed locations. DNS, recommendations, and serverless code are not the native governance control for this requirement.'),
  mc('governance-compliance','medium','Which service provides data discovery, classification, and governance across an organization’s data estate?','Microsoft Purview',['Azure Virtual Desktop','Azure VPN Gateway','Azure Queue Storage'],'Microsoft Purview provides data governance capabilities such as cataloging, classification, and lineage. The other options deliver desktops, network connectivity, or message storage.'),

  mc('management-deployment','easy','An administrator wants an authenticated browser shell with both Azure CLI and Azure PowerShell available. What should they open?','Azure Cloud Shell',['Azure Service Health','Azure Data Box','Application Insights'],'Cloud Shell supplies a browser-based authenticated shell with Azure command-line tools. The other services report health, transfer offline data, or monitor application behavior.'),
  mc('management-deployment','medium','A team needs declarative deployments that can be reviewed in source control and repeated across environments. Which approach should it use?','Infrastructure as code',['Manual portal creation only','Resource tags as deployment scripts','A monthly budget'],'Infrastructure as code captures desired resources in versioned definitions for repeatable, reviewable deployment. Tags and budgets are metadata and financial controls, while manual-only work is not a reusable definition.'),
  mc('management-deployment','medium','Which Azure control plane processes resource-management requests from the portal, CLI, PowerShell, templates, and REST APIs?','Azure Resource Manager',['Azure DNS','Azure Virtual Desktop','Azure Data Box'],'Azure Resource Manager is the common management and deployment layer for Azure resources. The other services resolve names, host desktops, or move data and are managed through that control plane.'),
  mc('management-deployment','hard','A company wants Azure governance and inventory for servers located on-premises and in another cloud. Which service should it use?','Azure Arc',['Azure Files','Azure Advisor','Azure ExpressRoute'],'Azure Arc projects supported non-Azure resources into Azure management so they can use inventory, policy, and related services. Files, Advisor, and ExpressRoute do not provide that hybrid control plane.'),
  mc('management-deployment','easy','Which language provides a concise Azure-native syntax that is compiled into an ARM template?','Bicep',['Kusto Query Language','AzCopy','Microsoft Entra ID'],'Bicep is a declarative language for Azure resource deployment and compiles to ARM template JSON. KQL queries telemetry, AzCopy transfers data, and Entra ID manages identity.'),

  mc('monitoring','easy','Which service provides personalized recommendations about Azure cost, reliability, security, operational excellence, and performance?','Azure Advisor',['Azure DNS','Azure Data Box','Microsoft Purview'],'Azure Advisor analyzes deployed resources and reports optimization recommendations across several pillars. DNS, offline transfer, and data governance do not provide this recommendation set.'),
  mc('monitoring','medium','An Azure incident is affecting resources in the company’s subscriptions. Which service shows personalized impact and updates?','Azure Service Health',['Azure Pricing calculator','Azure Policy','Azure Storage Explorer'],'Service Health reports active incidents, planned maintenance, and advisories relevant to a customer’s subscriptions. The alternatives estimate cost, assess configuration, or administer storage.'),
  mc('monitoring','medium','Operations needs an email when a virtual machine’s CPU metric remains above a threshold. What should be configured?','An Azure Monitor alert with an action group',['A resource delete lock','A Blob Storage access tier','A management group'],'Azure Monitor alert rules evaluate telemetry, and action groups specify notifications or automated responses. Locks, storage tiers, and governance hierarchy do not evaluate CPU metrics.'),
  mc('monitoring','hard','Developers need request rates, exceptions, dependencies, and distributed traces for a web application. Which Azure Monitor feature is designed for this?','Application Insights',['Azure Policy compliance','Microsoft Purview','Azure Cost Management'],'Application Insights provides application performance monitoring and traces requests through dependencies. The other services focus on configuration compliance, data governance, or expenditure.'),
];

const p2 = [
  dd('cloud-computing','easy','An environment that uses private infrastructure together with public-cloud services is a {{blank}} cloud.','hybrid',['public-only','serverless','software as a service'],'A hybrid cloud intentionally connects or coordinates private or on-premises resources with public-cloud services. Serverless and SaaS are consumption or service models, not the deployment model spanning both environments.'),
  sg('cloud-computing','medium','For each responsibility, decide whether it normally belongs to Microsoft when a customer uses Azure Software as a Service.','yes-no',[["Maintain the physical datacenter",true],["Decide which employees can access the customer’s data",false],["Classify the customer’s business records",false]],'Microsoft operates the cloud facilities and service platform. The customer still governs its identities, access, information classification, and appropriate use even when the complete application is provider managed.'),
  ms('cloud-computing','hard','Which TWO statements accurately describe a consumption-based cloud model?',['Monthly charges can change with usage','Resources can be released when they are no longer required'],['All capacity becomes a customer-owned capital asset','Every workload has the same fixed price regardless of consumption'],'Consumption pricing meters eligible resource use rather than requiring ownership of maximum capacity. This allows spending to vary and lets teams stop paying for released resources, subject to each service’s pricing terms.'),
  mc('cloud-computing','easy','A bank operates infrastructure dedicated to the bank in its own datacenter. Which deployment model does this describe?','Private cloud',['Public cloud','Hybrid cloud','Platform as a service'],'A private cloud is dedicated to one organization and can be located in its own facilities. No public-cloud component is described, and PaaS identifies a service type rather than infrastructure ownership.'),
  mc('cloud-computing','medium','A company moves from buying servers to paying monthly for Azure usage. How is the cloud spending normally categorized?','Operational expenditure (OpEx)',['Capital expenditure (CapEx) only','A physical inventory asset','Datacenter depreciation owned by Microsoft’s customer'],'Pay-as-you-go cloud service costs are operating expenses tied to consumption. Purchasing hardware creates a capital asset, which is the up-front model the company is replacing.'),

  dd('cloud-benefits','easy','Increasing the CPU and memory of one virtual machine is {{blank}} scaling.','vertical',['horizontal','geographic','serverless'],'Vertical scaling changes the capacity of an existing instance. Horizontal scaling changes the number of instances, while geographic and serverless do not name this resize direction.'),
  sg('cloud-benefits','medium','Evaluate each example of cloud predictability and governance.','true-false',[["Performance test results can help forecast capacity needs",true],["A cost estimate guarantees the exact future invoice",false],["Central policy can reduce configuration inconsistency",true]],'Predictability uses evidence to improve forecasts but cannot guarantee an exact future bill because usage and prices can vary. Governance applies organizational standards across resources.'),
  mc('cloud-benefits','medium','An application is deployed across fault-isolated locations so that it can recover from a location failure. Which benefit is the main goal?','Reliability',['Capital expenditure','Passwordless access','Data classification'],'Reliability is the ability to recover from failures and continue operating as designed. Financial treatment, authentication, and data labels do not describe the resilient architecture.'),
  mc('cloud-benefits','hard','Administrators use a portal, command line, APIs, and templates to control the same cloud resources. Which benefit is illustrated?','Manageability',['Physical ownership','Single tenancy','Data sovereignty'],'Multiple consistent management interfaces make resources easier to provision, configure, and automate. They do not establish who owns hardware, whether infrastructure is dedicated, or where data must reside.'),

  dd('service-types','easy','{{blank}} describes a complete subscription CRM application managed by its provider.','software as a service (SaaS)',['infrastructure as a service (IaaS)','platform as a service (PaaS)','a customer-managed hypervisor'],'SaaS provides the finished application and manages its underlying stack. IaaS and PaaS give customers infrastructure or an application platform on which they operate more of the solution.'),
  sg('service-types','medium','Evaluate each statement about customer control in cloud service types.','true-false',[["IaaS gives a customer control of the guest operating system",true],["PaaS requires the customer to maintain the physical hosts",false],["SaaS gives the customer administrator access to the provider’s application servers",false]],'Customers manage the guest OS in IaaS. Providers operate physical infrastructure in every cloud service type, and SaaS users configure the application without administering its underlying servers.'),
  ms('service-types','hard','Which TWO scenarios are best matched to platform as a service (PaaS)?',['Deploy a web app while the provider patches the runtime','Use a managed database while controlling schemas and data'],['Install a custom kernel driver on a guest operating system','Subscribe to a finished payroll application'],'PaaS manages the runtime or database platform while customers focus on their applications and data. Guest OS customization points to IaaS, and a complete payroll product is SaaS.'),
  mc('service-types','easy','A lift-and-shift migration places an unchanged legacy server on an Azure virtual machine. Which service type is used?','Infrastructure as a service (IaaS)',['Platform as a service (PaaS)','Software as a service (SaaS)','Managed productivity software'],'An Azure virtual machine exposes a customer-managed guest operating system, so it is IaaS. The application has not been redesigned for a managed platform or replaced by a provider application.'),
  mc('service-types','medium','In which service type does the provider manage the application, runtime, operating system, and physical infrastructure?','Software as a service (SaaS)',['Infrastructure as a service (IaaS)','Platform as a service (PaaS)','Customer-operated private cloud'],'SaaS places the complete application stack under provider operation, while customers manage their data, users, and configuration. IaaS and PaaS leave the customer responsible for the application.'),

  dd('azure-architecture','easy','The Azure hierarchy from broad to narrow is management group, subscription, resource group, and {{blank}}.','resource',['availability zone','region pair','Microsoft Entra tenant'],'An Azure resource is the manageable item inside a resource group. Availability zones and region pairs are physical-resiliency concepts, while a tenant is an identity boundary rather than the next child in this hierarchy.'),
  sg('azure-architecture','hard','Evaluate each statement about Azure regions and availability zones.','true-false',[["An Azure region contains one or more datacenters",true],["Every Azure region supports availability zones",false],["An availability zone is a billing container above a subscription",false]],'Regions are geographic deployment areas containing datacenters. Zone availability varies by region and service, and a zone is physical infrastructure—not a subscription or billing hierarchy scope.'),
  mc('azure-architecture','medium','Several application resources are deployed in different Azure regions but share one lifecycle. Can they be placed in one resource group?','Yes, a resource group can contain resources from different regions',['No, a resource group is an availability zone','No, every resource group is limited to one datacenter','Yes, but only if every resource has the same type'],'A resource group is a logical management container and can contain different resource types and locations. Its own stored metadata location does not force all contained resources into that region.'),
  mc('azure-architecture','hard','Governance must apply to four subscriptions without assigning the same rule four times. Where should the subscriptions be organized?','Under one management group',['Inside one resource group','Inside one availability set','Under one virtual network'],'A policy or access assignment at a management group can inherit to subscriptions beneath it. Resource groups cannot contain subscriptions, and availability sets or networks are workload constructs.'),

  dd('compute-networking','easy','A managed service for publishing web apps and REST APIs is Azure App {{blank}}.','Service',['Gateway','Monitor','Storage'],'Azure App Service hosts web applications and APIs on a managed platform with deployment and scaling features. The other completions refer to network, observability, or storage capabilities.'),
  sg('compute-networking','medium','For each connectivity requirement, decide whether Azure ExpressRoute is the best match.','yes-no',[["Use a provider connection that avoids the public internet",true],["Connect two Azure virtual networks with no circuit provider",false],["Resolve a public domain name to an IP address",false]],'ExpressRoute supplies private connectivity from an on-premises network through a connectivity provider. Virtual network peering joins Azure networks, and Azure DNS performs name resolution.'),
  ms('compute-networking','hard','Which TWO compute options package application dependencies in containers rather than requiring a full guest operating system for every instance?',['Azure Container Instances','Azure Kubernetes Service'],['Azure Virtual Desktop','Azure VPN Gateway'],'Container Instances and AKS both run container images, with AKS adding Kubernetes orchestration. Virtual Desktop supplies desktop sessions, and VPN Gateway connects networks instead of hosting application containers.'),
  mc('compute-networking','easy','Remote staff need personal and pooled Windows desktops delivered from Azure. Which service addresses the requirement?','Azure Virtual Desktop',['Azure Functions','Azure DNS','Azure Files'],'Azure Virtual Desktop delivers cloud-hosted Windows desktops and applications to users. Functions runs event code, DNS resolves names, and Files supplies shared storage.'),
  mc('compute-networking','medium','A branch office needs an encrypted tunnel to an Azure virtual network over its existing internet connection. What should it use?','Azure VPN Gateway',['Azure ExpressRoute only','Virtual network peering only','Azure Policy'],'VPN Gateway supports site-to-site encrypted connectivity across the public internet. ExpressRoute uses a private provider circuit, peering connects Azure virtual networks, and Policy governs configuration.'),

  dd('azure-storage','easy','Azure {{blank}} provides a shared SMB file system that cloud and on-premises clients can mount.','Files',['Queue Storage','Table Storage','Managed Disks'],'Azure Files provides managed file shares accessible through protocols such as SMB. Queues exchange messages, Tables store key-value entities, and managed disks attach block storage to virtual machines.'),
  sg('azure-storage','medium','Evaluate each statement about Blob Storage access tiers.','true-false',[["The hot tier is designed for frequently accessed data",true],["The archive tier offers immediate low-latency reads",false],["Changing tiers can affect storage and access charges",true]],'Hot storage favors frequent access, while archive data must be rehydrated before reading and can take hours. Tier selection trades storage price against access, transaction, and retrieval characteristics.'),
  ms('azure-storage','hard','Which TWO redundancy options copy data to a secondary Azure region?',['Geo-redundant storage (GRS)','Geo-zone-redundant storage (GZRS)'],['Locally redundant storage (LRS)','Zone-redundant storage (ZRS)'],'GRS and GZRS add asynchronous replication to a secondary region. LRS remains within one datacenter, while ZRS spreads synchronous copies across zones in one region.'),
  mc('azure-storage','medium','An application needs a durable queue so components can exchange messages asynchronously. Which storage service should it use?','Azure Queue Storage',['Azure Disk Storage','Azure Files','Azure DNS'],'Queue Storage holds messages that decouple application components and can be processed asynchronously. Disks and Files store block or file data, while DNS performs name resolution.'),
  mc('azure-storage','hard','Which redundancy choice writes synchronous copies across availability zones in the primary region and also replicates to a secondary region?','Geo-zone-redundant storage (GZRS)',['Premium block blob storage','Zone-redundant storage (ZRS)','Geo-redundant storage (GRS)'],'GZRS combines zonal protection in the primary region with geographic replication to a secondary region. ZRS lacks the secondary copy, GRS does not use primary-region zones, and premium is a performance tier.'),

  dd('identity-security','easy','{{blank}} uses signals such as user, device compliance, location, and risk to control sign-in.','Conditional Access',['Domain Services','Storage replication','Cost Management'],'Conditional Access evaluates identity and contextual signals to require controls such as MFA or block access. Domain Services supplies managed domain features, while storage and cost tools do not make sign-in decisions.'),
  ms('identity-security','hard','Which TWO capabilities can reduce reliance on reusable passwords?',['Multifactor authentication','Passwordless authentication'],['Resource tags','Storage lifecycle rules'],'MFA adds another proof to a password-based flow, and passwordless methods can replace the password with stronger factors. Tags and lifecycle policies manage resource metadata or data retention.'),
  mc('identity-security','easy','Users sign in once and then open several authorized applications without another prompt. Which capability is being used?','Single sign-on (SSO)',['Geo-redundant storage','Virtual network peering','A delete lock'],'SSO lets an authenticated identity access multiple authorized applications without repeating the entire sign-in process. The alternatives concern storage, networking, and resource protection.'),
  mc('identity-security','medium','A legacy application needs LDAP, Kerberos, and managed domain join, but the team does not want to deploy domain controllers. Which service fits?','Microsoft Entra Domain Services',['Azure RBAC','Azure Service Health','Azure Queue Storage'],'Microsoft Entra Domain Services provides managed domain capabilities compatible with many legacy workloads. RBAC authorizes Azure resource actions, while health and storage services solve unrelated problems.'),
  mc('identity-security','medium','Which security strategy uses controls at physical, identity, perimeter, network, compute, application, and data layers?','Defense in depth',['Consumption pricing','Horizontal scaling','Resource grouping'],'Defense in depth layers safeguards so one failed control does not expose the entire system. Pricing, scaling, and grouping do not describe a multilayer security model.'),

  sg('cost-management','medium','Evaluate each statement about Azure cost planning and analysis.','true-false',[["The Pricing calculator estimates a proposed deployment",true],["Cost analysis can report actual recorded charges",true],["A resource tag automatically discounts the tagged service",false]],'The calculator models expected prices before deployment, while Cost Management analyzes actual and forecast spend. Tags add allocation metadata but do not alter a service’s rate or usage.'),
  ms('cost-management','hard','Which TWO factors can change the price of an Azure solution even when its application code is unchanged?',['The Azure region selected for resources','The amount of outbound data transferred'],['The display name of a resource group','The order in which tags are entered'],'Azure service rates can vary by region, and outbound transfer can be metered. Names and tag ordering are management metadata with no direct price effect.'),
  mc('cost-management','easy','A team wants an email when forecast monthly spending approaches a target. What should it configure?','A Cost Management budget with alert conditions',['A resource lock','An availability set','A private endpoint'],'Budgets compare actual or forecast cost with defined thresholds and can trigger notifications. Locks, availability sets, and private endpoints do not monitor aggregate spending.'),
  mc('cost-management','medium','A stable eligible workload will run continuously for three years. Which option may lower its compute price in exchange for a commitment?','An Azure reservation',['A department tag','A public endpoint','A read-only lock'],'A reservation can provide discounted eligible usage for a committed term. Tags organize resources, endpoints provide connectivity, and locks protect changes without purchasing capacity.'),

  sg('governance-compliance','medium','Evaluate each statement about resource locks.','true-false',[["A delete lock can prevent an authorized user from deleting a resource",true],["A read-only lock allows ordinary update operations",false],["A lock grants a user permission to view a resource",false]],'Locks restrict control-plane changes even when RBAC would otherwise allow them. Read-only locks block updates, and locks never grant identity permissions; access must come from authorization such as RBAC.'),
  ms('governance-compliance','hard','Which TWO capabilities are associated with Microsoft Purview?',['Discover and catalog data assets','Classify sensitive information across a data estate'],['Scale a virtual machine set','Create an encrypted site-to-site VPN'],'Purview supports data governance through discovery, cataloging, classification, and lineage. Compute scaling and network tunneling are performed by other Azure services.'),
  mc('governance-compliance','easy','An audit needs a list of resources that violate an assigned secure-transfer rule. Which capability supplies the result?','Azure Policy compliance evaluation',['Azure DNS resolution','A reservation utilization report','Virtual network peering'],'Azure Policy evaluates resources against assigned definitions and reports compliant and noncompliant results. DNS, reservations, and peering do not assess resource configuration rules.'),
  mc('governance-compliance','medium','What is the key distinction between Azure Policy and Azure RBAC?','Policy evaluates resource state; RBAC authorizes user and service actions',['Policy manages DNS; RBAC selects storage tiers','Policy calculates bills; RBAC creates budgets','They provide identical controls under different names'],'Policy governs whether configurations meet rules, while RBAC governs which management operations an identity may perform at a scope. They complement rather than replace each other.'),

  mc('management-deployment','easy','A Linux administrator wants cross-platform commands such as az group create. Which tool should be installed?','Azure CLI',['Azure PowerShell','Azure Advisor','Azure Policy'],'Azure CLI uses az commands and works across common operating systems. Azure PowerShell uses cmdlets, while Advisor and Policy are cloud services rather than local command syntaxes.'),
  mc('management-deployment','medium','An administrator prefers object-based pipelines and commands such as New-AzResourceGroup. Which tool matches that preference?','Azure PowerShell',['AzCopy','Azure DNS','Microsoft Purview'],'Azure PowerShell supplies Az-module cmdlets and PowerShell objects for managing Azure. AzCopy transfers storage data, while DNS and Purview are services managed by such tools.'),
  mc('management-deployment','hard','A Bicep deployment runs again with no desired-state changes. What result should a declarative deployment aim for?','Keep resources in the declared state without duplicating them',['Create a second copy of every resource','Delete the subscription','Move all resources to a different tenant'],'Declarative infrastructure describes the intended end state, allowing repeated deployment to converge on that state. An unchanged definition should not imply duplicate infrastructure or unrelated destructive moves.'),
  mc('management-deployment','medium','What file format is used by an Azure Resource Manager template?','JSON',['A compiled executable','A DNS zone file only','A relational database'],'ARM templates are declarative JSON documents describing Azure resources and dependencies. Bicep offers another authoring syntax but compiles to the ARM JSON representation.'),
  mc('management-deployment','easy','An administrator wants a graphical browser interface for creating and managing Azure resources. Which tool is the direct fit?','The Azure portal',['AzCopy','Azure Data Box','Log Analytics'],'The Azure portal is the browser-based graphical management interface. AzCopy and Data Box move data, while Log Analytics is used to query monitoring logs.'),

  mc('monitoring','easy','Which Azure Monitor data type stores time-stamped numeric measurements such as CPU percentage?','Metrics',['Resource locks','Tags','Management groups'],'Metrics are lightweight numerical time-series values suitable for charts and threshold alerts. Locks, tags, and management groups are resource-management constructs, not telemetry records.'),
  mc('monitoring','medium','A team needs to query collected logs by using Kusto Query Language. Which Azure Monitor experience should it use?','Log Analytics',['Azure Advisor','Azure Pricing calculator','Azure DNS'],'Log Analytics provides KQL queries over Azure Monitor Logs workspaces. Advisor recommends improvements, the calculator estimates prices, and DNS resolves names.'),
  mc('monitoring','medium','Which service reports planned maintenance and health advisories relevant to a company’s Azure subscriptions?','Azure Service Health',['Azure status only','Azure Files','Microsoft Purview'],'Service Health supplies personalized notices for subscribed services and regions, including maintenance and advisories. The public status page is broad and not tailored to the customer’s resources.'),
  mc('monitoring','hard','A team receives an Azure Advisor recommendation. What should it assume?','The recommendation should be reviewed and is not automatically implemented in every case',['Advisor has already changed every affected resource','The recommendation is an active platform outage','Advisor has granted the team new RBAC permissions'],'Advisor analyzes configuration and proposes optimizations for review. It does not universally make the change, declare incidents, or alter identity permissions merely by issuing a recommendation.'),
];

const p3 = [
  dd('cloud-computing','easy','{{blank}} owns and operates the physical servers and facilities in a public cloud.','the cloud provider',['each application user','the customer’s internet provider','all subscribers jointly'],'The public-cloud provider owns and maintains the shared physical infrastructure and offers services to customers. Customers manage their own data, identities, configuration, and other responsibilities according to the service model.'),
  sg('cloud-computing','medium','Evaluate each statement about cloud deployment models.','true-false',[["A private cloud is dedicated to one organization",true],["A public cloud is operated by a provider for its customers",true],["A hybrid cloud must contain only public-cloud resources",false]],'Private cloud infrastructure is dedicated to one organization, while a provider operates public-cloud facilities for customers. Hybrid designs combine environments, so they are not restricted to public resources.'),
  ms('cloud-computing','hard','A team moves an application from customer-owned servers to Azure virtual machines. Which TWO financial or responsibility changes should it expect?',['Physical host maintenance transfers to Microsoft','Eligible resource charges can follow consumption'],['Microsoft becomes responsible for the application’s user accounts','The virtual machines become customer-owned datacenter hardware'],'Azure operates the physical hosts and meters cloud resources, but the customer still manages guest configuration, application identities, and data. Consuming a VM does not transfer ownership of Azure hardware.'),
  mc('cloud-computing','easy','A research organization alone uses a cloud environment hosted on dedicated infrastructure. Which deployment model is described?','Private cloud',['Public cloud','Hybrid cloud','Software as a service'],'A private cloud serves one organization on dedicated cloud infrastructure, whether hosted on-premises or by another party. No second environment is described, and SaaS is an application service type.'),
  mc('cloud-computing','medium','A web API runs on Azure App Service. Who is responsible for fixing a vulnerability in the API’s own code?','The customer that develops the API',['Microsoft because App Service is PaaS','The physical datacenter operator only','The customer’s DNS registrar'],'PaaS transfers operation of the host platform to Microsoft but not responsibility for customer application code and data. The development team must remediate vulnerabilities in what it builds.'),

  dd('cloud-benefits','easy','Adding more virtual machine instances behind a load balancer is an example of scaling {{blank}}.','out (horizontally)',['up (vertically)','to archive storage','into a private cloud'],'Horizontal or scale-out changes add instances so work can be distributed. Vertical scaling enlarges an existing instance, and the other choices are storage or deployment changes rather than scale directions.'),
  sg('cloud-benefits','medium','Evaluate each statement about availability, reliability, and governance.','true-false',[["High availability focuses on keeping a service accessible",true],["Reliability can use redundancy and recovery to tolerate failures",true],["Governance removes the need for all security controls",false]],'Availability and reliability use resilient design, redundancy, and recovery to meet service goals despite failures. Governance supplies oversight but complements rather than replaces security controls.'),
  mc('cloud-benefits','medium','A business wants to forecast both expected cloud cost and application performance before a release. Which cloud benefit is most relevant?','Predictability',['Single tenancy','Capital ownership','Data classification'],'Predictability uses pricing models, monitoring, and performance evidence to improve cost and performance forecasts. The other choices describe isolation, assets, or information governance.'),
  mc('cloud-benefits','hard','A platform restores service in another location after a regional failure. Which cloud benefit does that recovery capability primarily demonstrate?','Reliability',['Manual manageability','Passwordless authentication','Consumption pricing'],'Reliability includes recovering from failures and continuing to deliver intended function. Authentication and billing are unrelated, and manual management is not the core outcome of regional recovery.'),

  dd('service-types','easy','{{blank}} gives a customer the most control over guest operating systems and networking.','infrastructure as a service (IaaS)',['platform as a service (PaaS)','software as a service (SaaS)','managed productivity software'],'IaaS exposes virtualized infrastructure and leaves guest operating systems and much network configuration under customer management. PaaS and SaaS progressively shift more of the stack to the provider.'),
  sg('service-types','medium','For each scenario, decide whether it describes software as a service (SaaS).','yes-no',[["Employees use Microsoft 365 without managing its application servers",true],["The provider manages the application servers for a complete subscription product",true],["Developers deploy their own code to a provider-managed runtime",false]],'A complete provider-operated application is SaaS, as illustrated by Microsoft 365 and other subscription products. Deploying customer code to a managed runtime instead describes PaaS.'),
  ms('service-types','hard','Which TWO statements describe the platform-as-a-service responsibility model?',['The provider patches the operating system and managed runtime','The customer manages its application code and data'],['The customer replaces failed physical disks','The provider defines all customer business data classifications'],'PaaS lets the provider operate infrastructure and platform software while the customer owns the deployed application and its information. Physical repairs are provider tasks in all cloud models, but data classification remains with the customer.'),
  mc('service-types','easy','A company subscribes to a provider-managed payroll product and configures only users and business settings. Which service type is this?','Software as a service (SaaS)',['Infrastructure as a service (IaaS)','Platform as a service (PaaS)','Physical colocation'],'A finished payroll product consumed by subscription is SaaS. The customer does not operate infrastructure or deploy its own application onto a managed development platform.'),
  mc('service-types','medium','An administrator must install a custom network appliance that requires guest operating-system access. Which model is appropriate?','Infrastructure as a service (IaaS)',['Platform as a service (PaaS)','Software as a service (SaaS)','A managed office application'],'IaaS gives the customer administrative control of a virtual machine guest OS, which is necessary for the appliance. Managed platforms and finished SaaS applications do not expose that level of host control.'),

  dd('azure-architecture','easy','A geographic area containing one or more Azure datacenters is an Azure {{blank}}.','region',['resource group','management group','availability set'],'An Azure region is a geographic deployment area containing datacenter infrastructure connected by a low-latency network. Resource and management groups are logical scopes, and an availability set is a VM resiliency construct.'),
  sg('azure-architecture','medium','Evaluate each statement about Azure scopes.','true-false',[["A subscription can contain multiple resource groups",true],["A resource group belongs to one subscription",true],["An availability zone can contain subscriptions for billing",false]],'Subscriptions contain resource groups, and each resource group belongs to one subscription. Availability zones are physical fault domains inside regions, not logical billing containers.'),
  mc('azure-architecture','medium','An administrator moves a supported resource to another resource group in the same subscription. Does this action automatically change its Azure region?','No, changing the resource group does not itself relocate the resource',['Yes, it moves to the resource group’s metadata region','Yes, it moves to the nearest region pair','No, because Azure resources never have a region'],'Resource-group membership is a logical management relationship, not a data-plane relocation instruction. Regional movement requires a service-specific migration or redeployment where supported.'),
  mc('azure-architecture','hard','A resource group is deleted successfully. What normally happens to the resources contained by it?','The contained resources are deleted with the resource group',['They move to the subscription root','They become members of every other resource group','They are converted into management groups'],'A resource group is a lifecycle boundary; deleting it requests deletion of its contained resources. This is why related resources are commonly grouped and deletion must be treated as consequential.'),

  dd('compute-networking','easy','Use Azure {{blank}} when an on-premises network needs a private dedicated connection to Microsoft cloud services.','ExpressRoute',['VPN Gateway over the public internet','DNS','Policy'],'ExpressRoute uses a connectivity provider to establish private connectivity that does not traverse the public internet. VPN Gateway uses encrypted internet tunnels, while DNS and Policy solve different needs.'),
  sg('compute-networking','medium','Evaluate each statement about Azure compute choices.','true-false',[["Azure Functions can run code in response to events",true],["Azure Virtual Desktop is a DNS hosting service",false],["Azure App Service requires customers to patch its physical servers",false]],'Functions supplies event-driven serverless compute, and App Service is a provider-managed platform. Azure Virtual Desktop delivers Windows desktops and applications rather than authoritative DNS hosting.'),
  ms('compute-networking','hard','Which TWO requirements point to Azure Virtual Machines rather than a managed web or serverless platform?',['Administrator access to the guest operating system','Installation of legacy server software with custom dependencies'],['Automatic execution from an event with no server management','A complete hosted email product for end users'],'Virtual machines fit workloads that require OS-level control and unusual server dependencies. Event-only code is a Functions scenario, while a complete hosted product is SaaS rather than customer-managed compute.'),
  mc('compute-networking','easy','Which service hosts public or private DNS zones and answers name-resolution queries?','Azure DNS',['Azure Advisor','Azure Files','Azure Policy'],'Azure DNS hosts DNS domains on Azure name servers and resolves record queries. Advisor, Files, and Policy provide recommendations, storage, and governance instead of name resolution.'),
  mc('compute-networking','medium','A team wants a managed Kubernetes control plane for orchestrating many containerized services. Which service should it select?','Azure Kubernetes Service (AKS)',['Azure Container Instances only','Azure Virtual Desktop','Azure Data Box'],'AKS provides managed Kubernetes orchestration for scheduling, scaling, and operating container workloads. Container Instances runs containers without a full Kubernetes control plane, and the other services are unrelated.'),

  dd('azure-storage','easy','An Azure virtual machine uses a managed {{blank}} for durable block storage.','disk',['queue','table','DNS zone'],'Azure managed disks provide block storage volumes for virtual machines. Queues hold messages, Tables hold key-value entities, and a DNS zone contains name records.'),
  sg('azure-storage','medium','Evaluate each storage-service match.','true-false',[["Azure Files provides managed file shares",true],["Queue Storage is designed to attach an operating-system disk to a VM",false],["Table Storage is a relational SQL database service",false]],'Azure Files exposes file shares. Managed disks back VM volumes, Queue Storage holds messages, and Table Storage is a schemaless NoSQL key-value service rather than a relational database.'),
  ms('azure-storage','hard','Which TWO statements about locally redundant storage (LRS) are correct?',['It maintains multiple synchronous copies','Its copies remain within one physical datacenter in the primary region'],['It replicates to a secondary region','It distributes copies across availability zones'],'LRS protects against local disk and rack failures by keeping copies in one datacenter. Regional replication requires a geo option, and zonal distribution requires ZRS or GZRS.'),
  mc('azure-storage','medium','A developer wants a graphical desktop tool to browse blobs, file shares, queues, and tables. Which tool should be used?','Azure Storage Explorer',['Azure Service Health','Azure Pricing calculator','Azure Arc'],'Storage Explorer provides a graphical interface for multiple Azure Storage data services. The alternatives report health, estimate costs, or manage hybrid infrastructure.'),
  mc('azure-storage','hard','An on-premises Windows file server should cache an Azure file share and synchronize changes between locations. Which service supports this?','Azure File Sync',['Azure Data Box','Azure Migrate','Blob lifecycle management'],'Azure File Sync centralizes shares in Azure Files while Windows Servers cache frequently used data and synchronize changes. Data Box and Migrate support transfer projects, while lifecycle management changes blob tiers.'),

  dd('identity-security','easy','Authorization to create, read, update, or delete Azure resources is commonly assigned with Azure {{blank}}.','role-based access control (RBAC)',['Blob access tiers','Service Health','Data Box'],'Azure RBAC maps identities to permitted management actions at a scope. Storage tiers affect price and retrieval, Service Health reports incidents, and Data Box transfers data.'),
  ms('identity-security','hard','Which TWO capabilities are provided by Microsoft Defender for Cloud?',['Security posture recommendations','Workload threat protection'],['Public DNS registration','Blob access-tier selection'],'Defender for Cloud assesses security posture and can provide workload protections for supported resources. DNS management and storage-tier selection belong to different Azure services.'),
  mc('identity-security','easy','A user signs in with a FIDO2 security key instead of a password. Which category describes the method?','Passwordless authentication',['Resource authorization only','Storage encryption','Single-factor reusable-password authentication'],'A FIDO2 security key can authenticate a user without transmitting or entering a reusable password. It establishes identity; resource authorization remains a separate decision made after authentication.'),
  mc('identity-security','medium','Which Zero Trust principle assumes attackers may already be present and designs monitoring and segmentation accordingly?','Assume breach',['Trust the internal network','Use maximum privilege','Disable telemetry after authentication'],'Assume breach treats compromise as possible and limits blast radius through segmentation, monitoring, and response. Implicit trust, excessive privilege, and missing telemetry contradict Zero Trust.'),
  mc('identity-security','medium','A sign-in should be allowed only from compliant devices and should require MFA when risk is elevated. What should be configured?','Microsoft Entra Conditional Access',['Azure Storage lifecycle management','Microsoft Entra Domain Services','A resource lock'],'Conditional Access combines identity, device, location, and risk signals with access controls. Storage lifecycle, managed domain features, and locks do not evaluate sign-in context.'),

  dd('cost-management','easy','Metadata such as CostCenter=42 used to group resources in reports is an Azure {{blank}}.','tag',['availability zone','private endpoint','resource lock'],'Tags are name-value metadata used to organize resources and allocate costs. They do not create physical isolation, private network connectivity, or protection from management changes.'),
  ms('cost-management','hard','Which TWO Cost Management capabilities help a team control monthly expenditure?',['Budgets with threshold notifications','Cost analysis grouped by service or tag'],['Availability zones that cap invoices','Resource locks that discount consumption'],'Budgets alert against actual or forecast thresholds, and cost analysis exposes spending patterns for action. Zones improve resiliency and locks prevent changes; neither creates a financial discount.'),
  mc('cost-management','medium','Which Azure service can identify an underused virtual machine and recommend a smaller size to reduce cost?','Azure Advisor',['Azure Monitor metrics alone','Microsoft Entra ID','Azure Files'],'Azure Advisor turns utilization analysis into optimization recommendations such as resizing. Raw metrics provide evidence but not the Advisor recommendation, while identity and file services are unrelated.'),
  mc('cost-management','medium','A team stops a virtual machine but leaves it allocated. What must it do to stop the VM compute charge?','Deallocate the virtual machine',['Rename its resource group','Add a cost-center tag','Apply a delete lock'],'Compute billing for a standard VM stops when the VM is deallocated, though attached storage and other resources can still incur charges. Metadata and locks do not change allocation state.'),

  sg('governance-compliance','medium','Evaluate each proposed governance control.','yes-no',[["Use Azure Policy to require a cost-center tag",true],["Use Microsoft Purview to scale a virtual machine",false],["Use a resource lock to assign a user the Reader role",false]],'Azure Policy can require or remediate resource metadata. Purview governs data rather than compute size, and locks constrain changes without granting any identity permission.'),
  ms('governance-compliance','hard','Which TWO scopes can receive an Azure Policy assignment that then applies to resources beneath the scope?',['A management group','A subscription'],['An availability zone','A physical datacenter rack'],'Management groups and subscriptions are scopes in the Azure resource hierarchy and support policy assignment. Availability zones and racks are physical infrastructure concepts, not customer governance scopes.'),
  mc('governance-compliance','easy','A critical database must be readable and manageable but protected from accidental deletion. Which feature is the narrowest match?','A delete lock',['A read-only lock','A cost tag','A private endpoint'],'A delete lock blocks deletion while allowing authorized updates, which matches the stated requirement. A read-only lock would also block changes, and tags or endpoints do not prevent deletion.'),
  mc('governance-compliance','medium','A policy assignment at a management group affects an existing child subscription. Why?','Policy assignments inherit down the Azure resource hierarchy',['Availability zones copy the policy','The subscription becomes a resource group','A storage tier translates the rule'],'Azure governance assignments can inherit from management groups to child subscriptions, resource groups, and resources. Physical zones and storage configuration are unrelated to scope inheritance.'),

  mc('management-deployment','easy','Which pair of command environments can be selected within Azure Cloud Shell?','Azure CLI or Azure PowerShell',['AzCopy or Data Box','Azure Policy or Azure Advisor','Bicep or an availability zone'],'Cloud Shell offers Bash with Azure CLI or PowerShell with Azure PowerShell in an authenticated browser session. The other choices are transfer tools, services, or resource concepts rather than shell environments.'),
  mc('management-deployment','medium','Why should an ARM or Bicep definition be stored in source control?','To review, version, and repeat the declared infrastructure change',['To convert every workload to SaaS automatically','To guarantee that no resource can ever change','To replace Azure Resource Manager'],'Source control records infrastructure changes and supports review and repeatable releases. It does not change service models, eliminate all drift, or replace the control plane that performs deployment.'),
  mc('management-deployment','hard','A template contains a web app and its hosting plan. What is a key benefit of deploying them together?','Dependencies and configuration can be applied consistently as one repeatable deployment',['Both resources become free of charge','The template grants every user Owner access','The resources no longer use Azure Resource Manager'],'Declarative deployments coordinate related resources and dependencies consistently. Templates do not remove charges or authorization requirements, and Resource Manager remains the deployment control plane.'),
  mc('management-deployment','medium','A team wants to manage Azure from a local program rather than a portal or shell. Which interface can it call?','Azure Resource Manager REST APIs or an Azure SDK',['Azure Data Box hardware only','A Blob Storage access tier','An availability zone'],'Azure exposes management operations through Resource Manager APIs and supported SDKs, using the same control plane as other tools. Hardware, storage tiers, and physical zones are not programming interfaces.'),
  mc('management-deployment','easy','A developer edits a concise declarative file with symbolic resource names and then deploys it through Resource Manager. Which language is likely being used?','Bicep',['Kusto Query Language','SQL only','A DNS zone file'],'Bicep is Azure’s concise declarative infrastructure language and compiles to ARM templates. KQL and SQL query data, while a DNS zone file describes name records.'),

  mc('monitoring','easy','Before signing in, an operator wants a broad view of major Azure platform incidents worldwide. Which page should be checked?','Azure status',['Azure Policy compliance','Azure Advisor','Azure Storage Explorer'],'Azure status gives a public global view of service availability. After sign-in, Service Health offers more personalized impact information for the organization’s subscriptions.'),
  mc('monitoring','medium','A dashboard must combine charts of platform metrics with results from log queries. Which service is the common monitoring platform?','Azure Monitor',['Azure Files','Azure Policy','Cost tags'],'Azure Monitor collects and visualizes metrics and logs and supports dashboards, workbooks, queries, and alerts. Files stores data, Policy governs state, and tags provide metadata.'),
  mc('monitoring','medium','Which component defines who receives an email or which automation runs when an Azure Monitor alert fires?','An action group',['A management group','A resource group','An availability group'],'An action group is the reusable collection of notification and automation endpoints invoked by Azure Monitor alerts. The other group types organize governance, resources, or database availability.'),
  mc('monitoring','hard','A web request calls two downstream services, and developers need to follow the operation across all dependencies. What telemetry is most useful?','Application Insights distributed tracing',['A Cost Management budget','An Azure Policy initiative','A resource delete lock'],'Application Insights correlates requests and dependency telemetry so a transaction can be traced through distributed components. Financial, governance, and deletion controls do not record application call paths.'),
];

export const az900Definition = {
  examCode: 'AZ-900', idPrefix: 'az900', blueprintVersion: '2026-07-20', skillsDate: 'July 20, 2026',
  tags: ['az-900','azure','fundamentals','mock-exam'], references: refs,
  domains: [
    { id: 'cloud-concepts', title: 'Describe cloud concepts', weight: 28 },
    { id: 'architecture-services', title: 'Describe Azure architecture and services', weight: 38 },
    { id: 'management-governance', title: 'Describe Azure management and governance', weight: 34 }
  ],
  objectives: {
    'cloud-computing': { domainId: 'cloud-concepts' }, 'cloud-benefits': { domainId: 'cloud-concepts' }, 'service-types': { domainId: 'cloud-concepts' },
    'azure-architecture': { domainId: 'architecture-services' }, 'compute-networking': { domainId: 'architecture-services' }, 'azure-storage': { domainId: 'architecture-services' }, 'identity-security': { domainId: 'architecture-services' },
    'cost-management': { domainId: 'management-governance' }, 'governance-compliance': { domainId: 'management-governance' }, 'management-deployment': { domainId: 'management-governance' }, monitoring: { domainId: 'management-governance' }
  },
  papers: [
    { title: 'Cloud Foundations and Core Services', items: calibrateDifficulties(p1) },
    { title: 'Applied Azure Scenarios', items: calibrateDifficulties(p2) },
    { title: 'Architecture, Security, and Governance', items: calibrateDifficulties(p3) }
  ]
};
